language: php

sudo: false

before_script:
    - composer install --prefer-source --no-interaction --dev

script:
    - php vendor/bin/sculpin generate -vvv -n --env=prod > build_output.log
    - if grep -iq " ! \|notice\|error\|warning" build_output.log ; then return 1; fi

after_script:
    - cat build_output.log
