language: php

sudo: false

before_install:
    - curl -O https://download.sculpin.io/sculpin.phar
    - php sculpin.phar install -n -q

script:
    - php sculpin.phar generate -vvv -n --env=prod > build_output.log
    - if grep -iq "notice\|error\|warning" build_output.log ; then return 1; fi

after_script:
    - cat build_output.log
