name: Deploy build

on:
  push:
    branches: [ master ]
  pull_request: # Temporarily!
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          version: 2

      - name: Build
        run: |
          php7.4 vendor/bin/sculpin generate -vvv -n --env=prod > build_output.log
          if grep -iq "notice\|error\|warning" build_output.log ; then return 1; fi
      
      - name: Output
        run: cat build_output.log
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: phperspl/phpers-website:latest