name: Test build

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          version: 2

      - name: Build
        run: |
          php8.3 vendor/bin/sculpin generate -vvv -n --env=prod > build_output.log
          if grep -iq "notice\|error\|warning" build_output.log ; then return 1; fi
      
      - name: Output
        run: cat build_output.log
